server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8025
          predicates:
            - Path=/catalog/**
        - id: movie-service
          uri: http://localhost:8023
          predicates:
            - Path=/movies/**
