management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,mappings
  info:
    env:
      enabled: true
      
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest

  zipkin:
    base-url: http://localhost:9411/

# Configura los nomrbes de las colas que vamos a tener
queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueu