global-message: Configuration server is alive!

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,mappings
  info:
    env:
      enabled: true
      
spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled: true
