server:
  port: 8025
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalogs_database

message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  circuitbreaker:
    instances:
      series:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        allow-health-indicator-to-fail: false
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      series:
        wait-duration: 5000
        retry-exceptions:
          - feign.FeignException$InternalServerError
        max-attempts: 3
