server:
  port: 8025
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalogs_database

message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

movie-service:
  url: http://localhost:8023/movies/%s
serie-service:
  url: http://localhost:8024/series/%s