server:
  port: 8023
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies_database
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: drop-and-create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.mySQL5Dialect

message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
