server:
  port: 8082

logging:
  level:
    root: WARN

spring:
  zipkin:
    base-url: http://localhost:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

  sql:
    init:
      mode: always
      data-locations: classpath:/sql/init.sql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movies_database
    username: root
    password: root

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
