server:
  port: 8024

spring:
  data:
    mongodb:
      host: localhost
      username: root
      password: root
      port: 27017
      database: series_database

logging:
  level:
    org.springframework.security: DEBUG
