server:
  port: 8761

spring:
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

  server:
    enable-self-preservation: false

  instance:
    prefer-ip-address: true
